<a href="https://colab.research.google.com/github/Thecoder0012/Iris/blob/master/iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [94]:
# necessary imports (numpy,keras etc.)
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from keras.layers import Dense, Activation
from keras.models import Sequential, load_model
from keras import optimizers

In [95]:
# Define columns and read file
column_names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
csv_file = 'iris.csv'
df = pd.read_csv(csv_file, names=column_names)

# Replace the class values with integers.
flower_names = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
flower_integers = [0,1,2]
df['class'] = df['class'].replace(flower_names, flower_integers)



In [96]:
# Display all rows
pd.options.display.max_rows = None
pd.options.display.max_columns = None

# Split the dataset into input (X) and output (y) variables.
# Returns numpy array after .values.
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values


In [ ]:
# Define the model.
model = Sequential([
  Dense(10, activation='relu', input_dim=4,use_bias=True),
  Dense(3, activation='softmax',use_bias=True)
])

# Compile the model
adam = optimizers.Adam(learning_rate=0.01)
model.compile(optimizer=adam,
              loss='sparse_categorical_crossentropy')

# train dataset
model.fit(x, y, epochs=500, batch_size=4,verbose=0)

In [102]:
# Make predictions on new data
# sample data with 10 rows minus the last column
input_data = df.sample(20).iloc[:, :-1].values
df_data = pd.DataFrame(input_data)  # Create new data to predict
prediction = model.predict(df_data)
prediction = np.round(prediction, decimals=3)
print('Prediction:',prediction)

# index in array 0-2
for i in prediction:
  print(i.argmax())

1/1 [==============================] - 0s 21ms/step
Prediction: [[0.    0.142 0.858]
 [0.    0.046 0.954]
 [1.    0.    0.   ]
 [0.    0.    1.   ]
 [1.    0.    0.   ]
 [1.    0.    0.   ]
 [0.    0.021 0.979]
 [0.    0.998 0.002]
 [0.    0.999 0.   ]
 [0.    0.011 0.989]
 [1.    0.    0.   ]
 [0.002 0.998 0.   ]
 [1.    0.    0.   ]
 [1.    0.    0.   ]
 [0.    0.993 0.007]
 [0.001 0.999 0.   ]
 [1.    0.    0.   ]
 [0.    0.    1.   ]
 [0.    0.    1.   ]
 [0.    0.01  0.99 ]]
2
2
0
2
0
0
2
1
1
2
0
1
0
0
1
1
0
2
2
2


In [99]:
# save model
model.save("iris.h5")